---
title: "Real value of different portfolios to reach $1m in 2020"
output: pdf_document
---

```{r setup, include=FALSE}
rm(list=ls())
library(dplyr)
library(ggplot2)
library(tidyr)
library(lubridate)
library(reshape2)
knitr::opts_knit$set(root.dir = "C:\\Users\\juyil\\Dropbox\\Study\\GitHub\\How-to-Become-a-Millionnaire")
return = read.csv("datasets\\Inflation_Adjusted_Return.csv")
rob = read.csv("datasets\\Robert_Shiller_CPI_adjusted_Return.csv")
return = merge(return, rob, by=c("Year","Month"))
colnames(return)[18:19] = c("RS_adjusted_Price","RS_adjusted_GR")
```

### Inflation measures: CPI, CPIC, PPI, PCE
### Return types: GR(gross return), PR(price return)

```{r, echo=FALSE}
## Add&adjust Time&portfolio column
measures = c("CPI", "CPIC", "PPI", "PCE")
return_types = c("GR", "PR") ##GR: gross return, PR: price return
for (measure in measures){
  for (return_type in return_types){
    return[nrow(return),ncol(return)+1] = 1000000 ## To reach 1m after 2019 Dec
    names(return)[ncol(return)] = paste0(measure,"_",return_type,"_","portfolio")
  }
}
return = return[seq(dim(return)[1],1),]
for (i in 20:27){
  for (j in 2:nrow(return)){
    if (i==20 | i==21){ return[j,i]=return[j-1,i]/(1+return[j,i-14]) }
    if (i==22 | i==23){ return[j,i]=return[j-1,i]/(1+return[j,i-13]) }
    if (i==24 | i==25){ return[j,i]=return[j-1,i]/(1+return[j,i-12]) }
    if (i==26 | i==27){ return[j,i]=return[j-1,i]/(1+return[j,i-11]) }
  }
}

## Robert Shiller Adjusted returns
return[1,ncol(return)+1] = 1000000 ## To reach 1m after 2019 Dec
names(return)[ncol(return)] = "RS_GR_portfolio"
for (j in 2:nrow(return)){ return[j,28]=return[j-1,28]/(1+return[j,19]) }

return = return %>% mutate(Time=paste0(Year,'/',sprintf("%02d", return$Month),'/',01))
return$Time = as.Date(return$Time, format = "%Y/%m/%d")
return = return[seq(dim(return)[1],1),]
return = na.omit(return)
```


```{r, fig.height=3.5, fig.width=8, echo=FALSE, warning=FALSE}
# reshape data from wide to long format
long = melt(return, measure.vars=c('CPI_GR_portfolio','CPI_PR_portfolio','CPIC_GR_portfolio','CPIC_PR_portfolio','PPI_GR_portfolio','PPI_PR_portfolio','PCE_GR_portfolio','PCE_PR_portfolio','RS_GR_portfolio')) %>% select(Time, variable, value)
g = ggplot(long, aes(Time, value, shape = variable, color = factor(variable))) + 
  geom_line() +
  scale_x_date(date_breaks = "10 years")+
  labs(title="Starting portfolio real value to reach $1m in 2020", color = "Portfolio x Deflation \nmethod combinations")+
  ylab("Portfolio real value in US dollars")+
  guides(color = guide_legend(override.aes = list(size=3)))+
  theme_minimal()
print(g)

## Log-scaled portfolios
for (col in 20:28){return[col] = log(return[col])}
# reshape data from wide to long format
long = melt(return, measure.vars=c('CPI_GR_portfolio','CPI_PR_portfolio','CPIC_GR_portfolio','CPIC_PR_portfolio','PPI_GR_portfolio','PPI_PR_portfolio','PCE_GR_portfolio','PCE_PR_portfolio','RS_GR_portfolio')) %>% select(Time, variable, value)
g = ggplot(long, aes(Time, value, shape = variable, color = factor(variable))) + 
  geom_line() +
  scale_x_date(date_breaks = "10 years")+
  labs(title="Starting portfolio real value to reach $1m in 2020", color = "Portfolio x Deflation \nmethod combinations")+
  ylab("Portfolio real value in US dollars")+
  guides(color = guide_legend(override.aes = list(size=3)))+
  theme_minimal()
print(g)
```


```{r, echo=FALSE}
## Time taken from $0 to $1m
for (measure in measures){
  for (return_type in return_types){
    return[1,ncol(return)+1] = 0 ## To reach 1m after 2019 Dec
    names(return)[ncol(return)] = paste0(measure,"_",return_type,"_","t")
  }
}

## RS
return[1,ncol(return)+1] = 0 ## To reach 1m after 2019 Dec
names(return)[ncol(return)] = "RS_GR_t"

```

```{r, eval=FALSE, include=FALSE}
ptm = proc.time()
for (col in 29:37){
  for (i in 1:nrow(return)){
    ct = 0
    portfolio_value = 0
    temp = i
    fulfiled = T
    while (portfolio_value<1000000){
      if (temp==1){
        portfolio_value = portfolio_value+500
        temp = temp+1
      } else if (temp>nrow(return)){
        fulfiled = F
        break
      } else {
        if (col==29|col==30){portfolio_value = (portfolio_value+500)*(1+return[temp-1,col-23])}
        else if (col==31|col==32){portfolio_value = (portfolio_value+500)*(1+return[temp-1,col-22])}
        else if (col==33|col==34){portfolio_value = (portfolio_value+500)*(1+return[temp-1,col-21])}
        else if (col==35|col==36){portfolio_value = (portfolio_value+500)*(1+return[temp-1,col-20])}
        else if (col==37){portfolio_value = (portfolio_value+500)*(1+return[temp-1,col-18])}
        temp = temp+1
        # print(paste('col:',col,'ct:',ct,'portfolio:', portfolio_value))
      }
      ct = ct+1
    }
    if (fulfiled){return[i,col] = ct} else {return[i,col] = NA}
    if (i%%12==0){print(paste("Portfolio:",col,"Time:",return$Time[i],"t:",ct, "Time elapsed:", as.numeric(proc.time()-ptm)[3]))}
  }
}

save(return, file="Time to 1m.RData")
```


## Distribution of time taken from $0 to $1m for different portfolio x deflation method combinations
Red vertical lines in histograms represents the mean time for a portfolio to reach $1m

```{r, echo=FALSE, warning=FALSE, fig.height=3.5, fig.width=8}
load("Time to 1m.RData")

for (col in 29:37){
  ## Convert t to year scale
  return[col]=return[col]/12
  p=ggplot(return, aes_string(return[,col]))+
    geom_bar(fill=I("steelblue"),color="white", binwidth = 1)+
    labs(title=names(return)[col])+
    xlab("Time to reach $1m in years")+
    geom_vline(aes(xintercept = mean(return[,col],na.rm = TRUE)),col='red',size=2)+
    theme_minimal()+
    annotate("text", x=mean(return[,col],na.rm = TRUE)-1.5, y=30, label= paste("Mean:",round(mean(return[,col],na.rm = TRUE),1),"years"))
  print(p)
}
```

## PCE_PR portfolio never reaches $1m from any starting time since 1959 Feb.


```{r, echo=FALSE, warning=FALSE, fig.height=3.5, fig.width=8}
return.temp = return %>% 
  gather(Portfolio, t, c('CPI_GR_t','CPI_PR_t','CPIC_GR_t','CPIC_PR_t','PPI_GR_t','PPI_PR_t','PCE_GR_t','PCE_PR_t','RS_GR_t')) %>%
  select(Portfolio, t)
p = ggplot(return.temp, aes(x=Portfolio, y=t), color=as.factor(Portfolio)) + 
    geom_boxplot(fill=I("white"),color="steelblue")+
    xlab("Portfolio x Inflation adjustment method")+
    ylab("Time to $1m in years")+
    theme_minimal()+
    labs(title="Time to reach $1m for different portfolio&inflation adjustment combinations")+ 
    annotate("text", x=1, y=mean(return.temp$t,na.rm = TRUE)+2, label= paste("Mean:",round(mean(return.temp$t,na.rm = TRUE),1),"years"),color="blue")+
    geom_hline(aes(yintercept = mean(return.temp$t,na.rm = TRUE)),col='blue',lty=2,size=1)+
    stat_summary(fun.y=median, colour="red", geom="text", show_guide = FALSE, vjust=1.5, aes(label=round(..y.., digits=1)))+
    stat_summary(fun.y=median, colour="darkred", geom="point", hape=18, size=3,show_guide = FALSE)
print(p)

```






```{r, fig.height=3.5, fig.width=8, echo=FALSE, warning=FALSE}
unfulfiled_t = data.frame("Portfolio"='a',
                          "Unfulfiled.start.time"=as.Date("2019-12-01"),
                          "Unfulfiled.end.time"=as.Date("2019-12-01"),stringsAsFactors=FALSE)
for (col in 29:37){
  unfulfiled_t=rbind(list(as.factor(colnames(return)[col]),
                          as.Date(return$Time[which(is.na(return[col]))[1]]),
                          as.Date("2019-12-01")), unfulfiled_t)
}
unfulfiled_t=unfulfiled_t[-nrow(unfulfiled_t),]


ggplot() + 
  geom_linerange(data=unfulfiled_t, aes(y=Portfolio, xmin=Unfulfiled.start.time, xmax=Unfulfiled.end.time),size=1.5)+
    xlab("Start time")+
    ylab("Portfolio x Inflation adjustment method")+
    theme_minimal()+
    labs(title="Impossible start time to reach $1m in 2020")+ 
    annotate("text", x=min(unfulfiled_t$Unfulfiled.start.time), y=5.7, label=paste("aa",min(unfulfiled_t$Unfulfiled.start.time)),color="blue")+
    annotate("text", x=max(unfulfiled_t$Unfulfiled.start.time), y=2.7, label=max(unfulfiled_t$Unfulfiled.start.time),color="blue")+
    geom_point(data=unfulfiled_t,aes(Unfulfiled.start.time, Portfolio), color="lightblue",size=3)

```





