---
title: "Simulation"
output: pdf_document
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
source("R/Simulation-years.R")
```

# Non-Inflation Gross Return

## Bootstraping

```{r, echo=FALSE}
port <- Sim_Port(sp$GrossReturn, 40, simfun = Spl_Boot)
```

### 40 years
```{r, echo=FALSE}
Sim_Plot(port, 40) +
  scale_y_continuous(breaks=c(0,2500000, 5000000, 7500000, 10000000),labels = c("$0", "$2,500,000", "$5,000,000", "$7,500,000", "$10,000,000"))
```

### 35 years
```{r, echo=FALSE}
Sim_Plot(port, 35) +
  scale_y_continuous(breaks=c(0,2000000,4000000,6000000),labels = c("$0", "$2,000,000", "$4,000,000", "$6,000,000"))
```

### 30 years
```{r, echo=FALSE}
Sim_Plot(port, 30) +
  scale_y_continuous(breaks=c(0,1000000,2000000,3000000),labels = c("$0", "$1,000,000", "$2,000,000", "$3,000,000"))
```

### 25 years
```{r, echo=FALSE}
Sim_Plot(port, 25) +
  scale_y_continuous(breaks=c(0,500000,1000000,1500000),labels = c("$0", "$500,000", "$1,000,000", "$1,500,000"))
```

### 20 years
```{r, echo=FALSE}
Sim_Plot(port, 20)  +
  scale_y_continuous(breaks=c(0,200000,400000,600000,800000),labels = c("$0", "$200,000", "$400,000", "$600,000","$800,000"))
```

## Log-Normal Simulation

```{r, echo=FALSE}
LNport <- Sim_Port(sp$GrossReturn, 40, simfun = LN_Sim)
```

### 40 years
```{r, echo=FALSE}
Sim_Plot(LNport, 40) +
  scale_y_continuous(breaks=c(0,2500000, 5000000, 7500000, 10000000),labels = c("$0", "$2,500,000", "$5,000,000", "$7,500,000", "$10,000,000"))
```

### 35 years
```{r, echo=FALSE}
Sim_Plot(LNport, 35) +
  scale_y_continuous(breaks=c(0,2000000,4000000,6000000),labels = c("$0", "$2,000,000", "$4,000,000", "$6,000,000"))
```

### 30 years
```{r, echo=FALSE}
Sim_Plot(LNport, 30) +
  scale_y_continuous(breaks=c(0,1000000,2000000,3000000),labels = c("$0", "$1,000,000", "$2,000,000", "$3,000,000"))
```

### 25 years
```{r, echo=FALSE}
Sim_Plot(LNport, 25) +
  scale_y_continuous(breaks=c(0,500000,1000000,1500000),labels = c("$0", "$500,000", "$1,000,000", "$1,500,000"))
```

### 20 years
```{r, echo=FALSE}
Sim_Plot(LNport, 20)  +
  scale_y_continuous(breaks=c(0,200000,400000,600000,800000),labels = c("$0", "$200,000", "$400,000", "$600,000","$800,000"))
```

## When Hit $1m

### Simple Bootstraping
```{r, echo=FALSE}
Tab_Years(port,40)
```
### Log-Normal Simulation
```{r, echo=FALSE}
Tab_Years(LNport, 40)
```

## Terminal Values
### Simple Bootstrapping
```{r, echo=FALSE}
Table_Quan(port)
```

### Log-Normal Simulation
```{r, echo=FALSE}
Table_Quan(LNport)
```
