---
title: "S&P 500 Non-Inflation Gross Return Simulation"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r, echo=FALSE, message=FALSE, warning=FALSE}
source("R/Simulation-years.R")
```

# Bootstraping - 45 Years

```{r, echo=FALSE}
port <- Sim_Port(sp$GrossReturn, 45, simfun = Spl_Boot)

yBS <- Tab_Years(port,45)
year1m <- na.omit(yBS[,1])
ylabel <- paste0(floor(year1m),"y",round((year1m-floor(year1m))*12),"m")
yBS$`Time`[seq_along(ylabel)] <- ylabel

y <- data.frame(x=year1m,y=1000000,label=ylabel)
```

```{r, echo=FALSE, warning=FALSE, message=FALSE}
Sim_Plot(port, 45) +
  geom_text(data=y,aes(x=x-1,y=y-100000,label=label), size=3, angle=45)
# +
#   scale_y_continuous(breaks=c(0,2500000, 5000000, 7500000, 10000000),labels = c("$0", "$2,500,000", "$5,000,000", "$7,500,000", "$10,000,000"))
```
```{r, echo=FALSE}
like <- Likelihood(port)
tabletotal <- cbind(yBS,Table_Quan(port))
tabletotal$Percentile <- rownames(tabletotal)
```
```{r, echo=FALSE}
Sim_Table(t,"Simple Bootstrapping")
gt(data = like, rowname_col = "name") 
```


```{r, echo=FALSE, eval=FALSE}
### 35 years
Sim_Plot(port, 35) +
  scale_y_continuous(breaks=c(0,2000000,4000000,6000000),labels = c("$0", "$2,000,000", "$4,000,000", "$6,000,000"))
```


```{r, echo=FALSE, eval=FALSE}
### 30 years
Sim_Plot(port, 30) +
  scale_y_continuous(breaks=c(0,1000000,2000000,3000000),labels = c("$0", "$1,000,000", "$2,000,000", "$3,000,000"))
```

```{r, echo=FALSE, eval=FALSE}
### 25 years
Sim_Plot(port, 25) +
  scale_y_continuous(breaks=c(0,500000,1000000,1500000),labels = c("$0", "$500,000", "$1,000,000", "$1,500,000"))
```


```{r, echo=FALSE, eval=FALSE}
### 20 years
Sim_Plot(port, 20)  +
  scale_y_continuous(breaks=c(0,200000,400000,600000,800000),labels = c("$0", "$200,000", "$400,000", "$600,000","$800,000"))
```

# Log-Normal Simulation - 45 Years

```{r, echo=FALSE}
LNport <- Sim_Port(sp$GrossReturn, 45, simfun = LN_Sim)
yLN <- Tab_Years(LNport, 45)
year1m <- na.omit(yLN[,1])
ylabel <- paste0(floor(year1m),"y",round((year1m-floor(year1m))*12),"m")
yLN$`Time`[seq_along(ylabel)] <- ylabel

y <- data.frame(x=year1m,y=1000000,label=ylabel)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
Sim_Plot(LNport, 45) +
  geom_text(data=y,aes(x=x-1,y=y-100000,label=label), size=3, angle=45)
# +
  # scale_y_continuous(breaks=c(0,2500000, 5000000, 7500000, 10000000),labels = c("$0", "$2,500,000", "$5,000,000", "$7,500,000", "$10,000,000"))
```
```{r, echo=FALSE}
like <- Likelihood(LNport)
tabletotal <- cbind(yLN,Table_Quan(LNport))
tabletotal$Percentile <- rownames(tabletotal)
```
```{r, echo=FALSE}
Sim_Table(t,"LogNormal Parametric Simulation")
gt(data = like, rowname_col = "name")
```

```{r, echo=FALSE, eval=FALSE}
### 35 years
Sim_Plot(LNport, 35) +
  scale_y_continuous(breaks=c(0,2000000,4000000,6000000),labels = c("$0", "$2,000,000", "$4,000,000", "$6,000,000"))
```

```{r, echo=FALSE, eval=FALSE}
### 30 years
Sim_Plot(LNport, 30) +
  scale_y_continuous(breaks=c(0,1000000,2000000,3000000),labels = c("$0", "$1,000,000", "$2,000,000", "$3,000,000"))
```

```{r, echo=FALSE, eval=FALSE}
### 25 years
Sim_Plot(LNport, 25) +
  scale_y_continuous(breaks=c(0,500000,1000000,1500000),labels = c("$0", "$500,000", "$1,000,000", "$1,500,000"))
```

```{r, echo=FALSE, eval=FALSE}
### 20 years
Sim_Plot(LNport, 20)  +
  scale_y_continuous(breaks=c(0,200000,400000,600000,800000),labels = c("$0", "$200,000", "$400,000", "$600,000","$800,000"))
```
