---
title: "Untitled"
author: "Leila Lei"
date: "8/6/2020"
output: pdf_document
---

```{r setup, include=FALSE}
library(dplyr)
rm(list=ls())

## sp: 1926/01/30-2019/12/31, monthly
sp = read.csv("../datasets/sp500 returns.csv")
## inf.crsp: 1926/01/30-2019/12/31, monthly
inf.crsp = read.csv("../datasets/inflation-crsp.csv")
## inf.cpi: 1913 Jan-2014 Jun, yearly
inf.cpi = read.csv("../datasets/Inflation-CPI_clean.csv")
```



Return based on 2020 dollar value & crsp inflation rate
```{r}
sp = sp[-1,1:3]
colnames(sp) = c("sp.t", "GrossReturn", "PriceReturn")
sp$GrossReturn = sp$GrossReturn+1
sp$PriceReturn = sp$PriceReturn+1

inf.crsp = inf.crsp[-1,1:2]
colnames(inf.crsp) = c("inf.crsp.t", "inf.crsp")
inf.crsp$inf.crsp = inf.crsp$inf.crsp+1

## total: 1926/03/31-2019/12/31, 1126 rows
total = cbind(sp,inf.crsp)[c(-1,-2),]
# total

total = total %>% mutate(crsp.adj.GR = GrossReturn/inf.crsp-1) %>% mutate(crsp.adj.PR = PriceReturn/inf.crsp-1)
## first row gives incorrect adjusted value
total = total[-1,]
write.csv(total, file="../datasets/inflation adjusted returns(crsp inf rate).csv")

# tail(total)
total
```


Return based on 2020 dollar value & cpi index
```{r}
# inf.cpi %>% mutate(inf.cpi = (CPI-lag(CPI))/lag(CPI))
# 
# ## total: 1926/03/31-2019/12/31, 1126 rows
# total = cbind(sp,inf.crsp)[c(-1,-2),]
# # total
# 
# total = total %>% mutate(adjusted.GR = GrossReturn/inf.crsp-1) %>% mutate(adjusted.PR = PriceReturn/inf.crsp-1)
# ## first row gives incorrect adjusted value
# total = total[-1,]
# write.csv(total, file="../datasets/inflation adjusted returns(2020 base).csv")
# 
# # tail(total)
# total
```